# aig/ — параллелизм, безопасность, тесты на больших n

Анализ всех пяти функций трансляции в этой папке (`tt_to_aig`, `aig_to_bdd`,
`aig_to_anf`, `aig_to_thr`, `aig_to_tt`) по трём осям: соответствие
`core/CONVENTIONS.md` п.6 (какой параллелизм положен по правилам), реальная
потокобезопасность реализации, и поведение на входах вплоть до n=64. Как и
`anf/README.md` — это рассуждения, а не описание API (см. `.hpp`) и не
журнал изменений (см. `git log`).

## Сводка: состояние и качество всех пяти функций

Быстрый ориентир перед тем, как читать разделы ниже целиком. Столбец
"качество" — не оценка стиля, а вывод из конкретных находок (TSan,
реальные дедлоки, замеры) в соответствующем разделе; "риски" — то, что
осталось открытым, а не гипотетическое.

| Функция | Корректность | Параллелизм | Качество | Открытые риски |
|---|---|---|---|---|
| `tt_to_aig` | PASS (ground_truth+metamorphic+sat_encoding); полный `ctest` 36/36, 145с | TBB `task_group`, **реальный дедлок найден и исправлен** этой сессией (см. §1.1) | Хорошее после фикса; `net_mutex` сериализует все мутации сети — архитектурное ограничение, не баг | Нет открытых; эффект `net_mutex` теоретический, не подтверждён на n<=16 |
| `aig_to_bdd` | Проверено на структурном корпусе до n=64, 200 случайных точек/семейство — 0 расхождений | Нет и не должно быть (только Sylvan/Lace, правило 1 из `CONVENTIONS.md` п.6) | Простой, однопоточный по построению, PI-порядок фиксированный натуральный | Нет открытых |
| `aig_to_anf` | PASS (ground_truth+metamorphic, n=1..12); реально пересобрано и прогнано в Docker в этой сессии (см. §6) | TBB формально требуется правилом, но **обоснованно отсутствует** в активной (BRiAl) ветке — BRiAl не потокобезопасен, подтверждено TSan (см. §1.3); в `AnfFallback`-ветке TBB реально работает, но не окупается (см. §4а) | Переписан в этой сессии: топологический проход вместо рекурсии+`shared_ptr`+хэш-таблицы, добавлены отсечки `isZero/isOne/p0==p1`, `Anf::evaluate` избавлен от `substitute_variables`. 0.02-0.06 мс/вызов (было медленнее и без отсечек) | `get_ring()` — кэш на один слот по "последнему n", не потокобезопасен при конкурентных вызовах с разными n (см. §6); `core/CONVENTIONS.md` формально не делает исключения для BRiAl-веток (только код это объясняет) |
| `aig_to_thr` | Покрыт тем же тестовым прогоном, что и остальные (`run_translation_tests`) | `tbb::parallel_for` — образцовый паттерн (см. §1.4): flat POD-структуры перед параллельным участком, честный измеренный speedup 0.94→1.14→**1.53** (n=8→12→14) | Лучший пример параллелизма в папке — стоит копировать этот паттерн, а не паттерн `aig_to_anf` | ILP получает до ~16М ограничений при n близко к `kMaxTruthTableVars=24` — не проверено эмпирически, вероятное узкое место (см. §1.4) |
| `aig_to_tt` | Покрыт тем же тестовым прогоном | OpenMP по блокам из 1024 точек (было 64 — расширено, см. §1.5), безопасность доказана чтением `mockturtle::simulate` (нет разделяемого mutable state) | Абсолютное время ускорено в 4-7 раз (устранены лишние аллокации на блок), но относительный speedup параллели к однопоточке остался ~1.0x — параллелизм сам по себе не окупается на тестируемых размерах (см. §1.5) | Не проверено под TSan (структурная причина безопасности не требовала эмпирического подтверждения); честный speedup для параллелизма как такового не достигнут |

## 0. Почему не все пять функций тестировались на n=64

`tt_to_aig` принимает `TruthTable` — по определению `n_vars() <=
kMaxTruthTableVars = 24` (`core/common.hpp`), больших входов физически не
существует. `aig_to_thr`/`aig_to_tt` принимают `Aig` произвольного размера,
но **сами** отклоняют `n_vars() > kMaxTruthTableVars` (`TooManyVariables`)
на первой строке, потому что их выход требует материализовать 2^n точек
(таблицу истинности или прогнать по ней ILP). Значит **только `aig_to_bdd`
и `aig_to_anf`** способны в принципе принять `Aig` с n=64 — тестирование "до
64 переменных" относится к ним; `tt_to_aig`/`aig_to_thr`/`aig_to_tt`
протестированы на максимуме, который они вообще допускают (n=24 и меньше),
отдельно.

## 1. Параллелизм и безопасность по функциям

### 1.1. `tt_to_aig` — НАЙДЕН И ИСПРАВЛЕН реальный дедлок

Первая (статическая) ревизия этого раздела ошибочно назвала мемоизацию
"структурно корректной" — double-checked locking (`std::atomic<bool>
ready` + `std::mutex mtx` на запись `entry->val`) сам по себе безопасен
как ИЗОЛИРОВАННЫЙ паттерн, но здесь `std::lock_guard<std::mutex>
lock(entry->mtx)` был взят **на всё время рекурсивного построения узла**,
включая вложенный `tg.wait()` — то есть поток, ожидающий чужой
`entry->mtx` (другой узел, который параллельно строит другой поток), сам
становится недоступен планировщику TBB как воркер. Статический анализ этого
не поймал; поймала находка совсем другого рода — исправление методологии
бенчмарков (см. §4 ниже, по запросу пользователя "исправь тесты, чтобы были
адекватные данные"): переход на медиану из 5 повторов вместо одного замера
увеличил число вызовов `tt_to_aig` в этом тесте, и на структурно
симметричной bench-функции ("majority"-подобная, много совпадающих
кофакторов у разных ветвей → много конкурентных попаданий на ОДИН и тот же
memo-ключ) реальный прогон `ctest` **завис на 25 минут** и упёрся в таймаут
CTest — тест провалился.

**Диагностика**: отдельный контейнер (без `--rm`, чтобы не терять процесс),
воспроизведено зависание, снят стек всех потоков (`cuda-gdb -p <pid> -batch
-ex "thread apply all bt"` — обычного `gdb` в образе нет, `cuda-gdb`
прекрасно работает и для host-процессов). Картина недвусмысленная: главный
поток (`ps -T`) — 3 секунды CPU за 60 секунд реального времени, ВСЕ
TBB-воркеры — 0 секунд CPU (полностью простаивают, не считают). Стек
показал несколько потоков в `pthread_mutex_lock()` на `tt_to_aig.cpp:113`
(тот самый `lock_guard`) на РАЗНЫХ адресах мьютекса (разные memo-записи),
пока потоки, реально считающие эти записи, сами вложены в
`tbb::detail::d1::task_group_base::wait()`, ожидая задачу, которую
исполнять уже некому — классический TBB-антипаттерн "блокирующий
ОС-примитив внутри кооперативного планировщика" исчерпывает арену:
воркеры либо заблокированы на `mutex.lock()` (не участвуют в
work-stealing), либо сами `tg.wait()`-ят за исполнителя, которого нет.

**Исправлено**: `entry->mtx` теперь защищает только МГНОВЕННУЮ публикацию
готового результата (без рекурсии внутри критической секции) — если поток
обнаруживает, что нужный узел ещё не готов, он не блокируется в ожидании
чужой работы, а считает его сам, избыточно (mockturtle структурно хэширует
одинаковые AND-узлы, так что повторный `create_and` для тех же аргументов
почти всегда не создаёт нового узла — избыточность практически бесплатна;
в худшем случае — несколько лишних неиспользуемых узлов в сети, не баг
корректности). Блокирующего ожидания чужой работы больше нет вообще —
цепочка "жду мьютекс → держащий его сам ждёт свободный поток" структурно
невозможна. Проверено: 5 повторных прогонов `tt_to_aig_tbb_scaling` подряд
после фикса — ни одного зависания, каждый укладывается в 1-2 секунды;
корректность (`tt_to_aig` секция, ground_truth+metamorphic+sat_encoding) —
PASS; полный `ctest` — 36/36, 145с (было зависание на 25 минут до фикса,
~120с до всех изменений этой сессии).

**Отдельно про `net_mutex`** (собственная находка первой ревизии, остаётся
в силе): все три мутирующие операции над общей `mockturtle::aig_network`
(`get_constant_safe`/`create_and_safe`/`create_or_safe`) защищены ОДНИМ
общим мьютексом — реальное построение AIG полностью сериализовано,
параллелится только вычисление кофакторов
(`kitty::cofactor0/cofactor1`) между двумя рекурсивными вызовами. Это НЕ
источник дедлока (обычный короткий mutex без вложенной блокирующей
рекурции внутри), но ограничивает потенциальный выигрыш от параллелизма.
Замерено эмпирически ПОСЛЕ обоих фиксов (`benchmarks/tbb_scaling.hpp`,
медиана 5 повторов + 1 прогрев, n=8/12/16 — единственные размеры, реально
доступные этой функции: вход `TruthTable` капнут `kMaxTruthTableVars=24`):
пять независимых прогонов дают spread ~0.5x-1.5x БЕЗ устойчивого
направления — честный вывод бенчмарка теперь "результат непоследователен
между размерами... не делайте выводов по одному размеру", а не ложно
уверенное "медленнее в 4 раза", которое печатал единичный замер до фикса
методологии. Реальный эффект `net_mutex`-сериализации на этих (суб-мс)
размерах неотличим от шума измерения — потенциально сдерживающий эффект
есть теоретически, но эмпирически не подтверждён и не опровергнут на
доступном этой функции диапазоне n.
(вход — `TruthTable`, ограничен n<=24 по определению, а таблица там жёстко
кэп 2^24 точек — уже дорогая сама по себе для построения `TruthTable`, не
входит в скоуп этого анализа).

**Дополнение (найдено `benchmarks/large_scale_bench.cpp`, по запросу
пользователя "построй сравнительную таблицу без ограничения в 12
переменных, без полного перебора"):** независимый от §1.1 второй реальный
перф-баг, на этот раз не дедлок, а честная сериализация. На **случайных**
(не "majority"-подобных, как в `tbb_scaling.hpp`) truth table мемоизация
по `(tt, var_idx)` почти не даёт коллизий — рекурсия реально исследует
близко к 2^n узлов, и на каждый такой узел раньше приходилось **три**
отдельных захвата `net_mutex` (`create_and_safe` ×2 + `create_or_safe` ×1
внутри построения мультиплексора). При миллионах узлов и параллельных
TBB-задачах (`var_idx>=12`) это means миллионы лишних циклов lock/unlock
под contention поверх тривиальной полезной работы (один хэш-lookup в
mockturtle на каждый лог). Три критические секции объединены в одну
(`build_mux_safe`) — то же количество полезной работы, втрое меньше
захватов мьютекса на узел:

| n | до фикса, speedup | после фикса, speedup |
|---|---|---|
| 16 | 9.06x | 12.01-12.78x |
| 20 | 7.72x | 7.92-8.25x |

Не устраняет сам экспоненциальный рост числа узлов на неструктурированном
входе (неизбежное свойство точного синтеза AIG по произвольной truth
table), только накладные расходы синхронизации сверх него. Проверено:
`test_aig --section tt_to_aig` PASS после фикса.

### 1.2. `aig_to_bdd` — корректно следует правилу 1

Нет собственного параллелизма (только Sylvan/Lace через `&`/`!` у
`sylvan::Bdd`), простой топологический обход `net.foreach_gate`,
мемоизация — плоский `std::vector<sylvan::Bdd>` по `node_to_index`. Никаких
проблем безопасности — однопоточный код по построению. Единственная
переменная, которая могла бы повлиять на размер результата — порядок PI
(здесь фиксированный, натуральный, `bddVar(pi_idx)` в порядке
`foreach_pi`) — в отличие от `anf_to_bdd` (см. `anf/README.md`), здесь нет
выбора эвристики, поэтому нечего сравнивать помимо самого размера итогового
BDD на разных структурах (см. §2).

### 1.3. `aig_to_anf` — САМАЯ ВАЖНАЯ находка сессии

Код содержит развилку по `BMM_HAVE_BRIAL`:

```cpp
#if BMM_HAVE_BRIAL
    PolType p0_val = apply_comp(get_anf_rec(child0), ...);   // ПОСЛЕДОВАТЕЛЬНО
    PolType p1     = apply_comp(get_anf_rec(child1), ...);
#else
    tbb::task_group tg;
    tg.run([&] { p0 = get_anf_rec(child0); });                // ПАРАЛЛЕЛЬНО
    PolType p1 = get_anf_rec(child1);
    tg.wait();
#endif
```

**TBB-форк по двум фанинам работает ТОЛЬКО в fallback-ветке
(`AnfFallback`, без BRiAl) — в реальной сборке (`BMM_HAVE_BRIAL=1`, как в
этом контейнере и как ожидается в production) код полностью
последовательный**, несмотря на то что `core/CONVENTIONS.md` п.6 правило 2
формально требует TBB для этой функции. Раньше (см. память сессии
`bmm_translib_anf_parallelism_work.md`) это было замечено, но не
задокументировано и не проверено — "похоже на осознанную предосторожность
... но нигде не задокументировано".

**Проверено эмпирически в этой сессии, окончательно:**

1. **ThreadSanitizer подтверждает: BRiAl (`libbrial`/PolyBoRi) НЕ
   потокобезопасен.** Стресс-тест (8 потоков × 2000 итераций конкурентного
   `ring.variable(idx) * ring.variable(idx2)` на одном `BoolePolyRing`, без
   мьютекса) под `-fsanitize=thread` даёт **7 подтверждённых data race**
   ровно там, где и следовало ожидать структурно: `polybori::CCuddCore::
   release()` — нессинхронизированный decrement счётчика ссылок у
   обёрнутого CUDD-менеджера (`BoolePolyRing` физически оборачивает
   `CCuddCore`, т.е. классический CUDD-style ZDD-менеджер — та же
   архитектура, из-за которой в этом же проекте выбран Sylvan вместо CUDD
   для BDD, см. `core/CONVENTIONS.md` — CUDD никогда не проектировался как
   потокобезопасный). Осторожность в `aig_to_anf.cpp` **оправдана**, это не
   лишняя перестраховка.
2. **Заявленный TBB-параллелизм в текущей (BRiAl) сборке — иллюзорный.**
   Первый прогон бенчмарка "1 поток vs все ядра" без прогрева дал
   обманчивые ускорения 20x-90x — оказалось артефактом: `get_ring(n)` в
   `aig_to_anf.cpp` кэширует ОДИН `BoolePolyRing` на "последний
   использованный n" (`static std::unique_ptr<BoolePolyRing> active_ring`);
   первый по счёту вызов с НОВЫМ n платит цену пересоздания ring (аллокация
   нового CUDD-менеджера), второй — уже тёплый кэш. Раз я мерил "1 поток"
   первым, а "все ядра" вторым при одном и том же n — разница была чисто
   про warmup, не про потоки. После добавления прогрева (одного лишнего
   вызова перед обоими замерами) реальная "разница между 1 потоком и всеми
   ядрами" на структурном корпусе (chain/star/block/mux/random, n=16..64)
   легла в диапазон **0.99x-1.9x** без какой-либо закономерности от
   размера — то есть шум измерения вокруг 1.0x, ровно то, что ожидается от
   кода, где параллельных задач физически не создаётся.

**Итог**: `aig_to_anf` не соответствует требованию TBB из
`core/CONVENTIONS.md` п.6 в actively используемой конфигурации сборки, и
это, по всей видимости, правильное решение по существу (не баг) — но
формулировка правила в CONVENTIONS.md не делает для этого случая
исключения, и решение нигде не объяснено с доказательствами до этой
сессии. Рекомендация: явно задокументировать в `aig_to_anf.hpp`/
`CONVENTIONS.md`, что BRiAl (в отличие от `AnfFallback`) не
поддерживает конкурентное построение полиномов на одном ring, со ссылкой
на этот файл — а не оставлять `#if BMM_HAVE_BRIAL` без обоснования.
Обязательный бенчмарк `aig_to_anf_tbb_scaling` в `test_aig.cpp` формально
проходит (тест лишь проверяет, что функция реализована, не требует
минимального speedup) — но печатаемое им число ("ускорение xN") в текущем
виде **вводит в заблуждение**: без понимания про `get_ring` warmup и про
BRiAl-ветку легко принять шумовые 1.0-1.3x (или, того хуже, случайно
незамеренный warmup-артефакт) за настоящий параллелизм.

**Дополнение (по итогам фикса дедлока в `tt_to_aig.cpp`, §1.1)**: у
`AnfFallback`-ветки (`#else` в блоке выше) обнаружен ТОТ ЖЕ дедлок-паттерн
— `std::lock_guard<std::mutex> lock(entry->mtx)` держался поперёк
`tg.run()`/`tg.wait()`. В текущей сборке (`BMM_HAVE_BRIAL=1`) эта ветка
никогда не выполняется (BRiAl-путь последователен), поэтому баг не
проявлялся эмпирически и не был бы пойман никаким прогоном тестов в ЭТОМ
образе — только чтением кода. Исправлен тем же способом, что и
`tt_to_aig.cpp` (mutex защищает только мгновенную публикацию, без
блокирующего ожидания чужой работы). **Не проверено живым прогоном** — в
этом Docker-образе BRiAl — системный заголовок, доступный по умолчанию
всем единицам трансляции; форсировать `BMM_HAVE_BRIAL=0` для конкретно
этого файла без пересборки образа без BRiAl не получилось в разумное
время. Корректность проверена только для АКТИВНОЙ (BRiAl) ветки — там
логика публикации результата общая для обеих веток (единственное отличие
— вокруг чего именно стоит `#if`), так что риск регрессии в BRiAl-пути
минимален, но `AnfFallback`-путь остаётся непроверенным вживую.

### 1.4. `aig_to_thr` — TBB, корректный и полезный паттерн

`tbb::parallel_for` по `[0, 2^n)` симулирует AIG на всех точках. Перед
параллельным участком узлы AIG вытащены в плоский `std::vector<FlatGate>`
(структуры POD, без указателей на `mockturtle::aig_network`) — это ровно
тот паттерн, который в памяти проекта отмечен как правильный ("вытащи
мономы/узлы в обычный vector до параллельного участка"). Каждый поток
работает со своим локальным `node_vals` буфером и пишет только в свой слот
`tt[idx]` — никакой разделяемой мутабельной памяти между потоками, гонок
структурно быть не может. Замер (1 прогрев + 1 поток vs все ядра):

| n | 1 поток, мс | все ядра, мс | speedup |
|---|---|---|---|
| 8  | 15.5  | 16.4  | 0.94 |
| 12 | 516.0 | 451.9 | 1.14 |
| 14 | 1797.4| 1172.8| **1.53** |

Растущее ускорение с ростом n — ожидаемо: полное время функции = симуляция
(параллельная) + ILP-solve (последовательный, не параллелится, см.
`aig_to_thr.hpp`); по мере роста n доля симуляции в общем времени растёт
быстрее (2^n) относительно ILP (число ограничений тоже растёт как 2^n, но
solve — не наивная точка-за-точкой работа), поэтому Amdahl-эффект даёт
всё больший выигрыш. Единственная практическая забота — при n, близких к
`kMaxTruthTableVars=24`, ILP получает **до 16 миллионов** ограничений (по
одному на точку) — не проверялось эмпирически в этой сессии, является
вероятным узким местом при больших n (см. `aig_to_thr.hpp`, комментарий уже
предупреждает об этом).

### 1.5. `aig_to_tt` — OpenMP, безопасность подтверждена, но узкое место — не гонки, а аллокации

`#pragma omp parallel for` по блокам, каждый поток создаёт СВОЙ
`custom_block_simulator` и вызывает `mockturtle::simulate<kitty::
static_truth_table<K>>(net, sim)` на общей `const` сети `net`. Проверено
по исходнику `mockturtle/algorithms/simulation.hpp`: `simulate()` строит
**локальный** `node_map` (`simulate_nodes` внутри, через
`std::make_shared<std::vector<T>>(ntk.size())`) на каждый вызов — не
хранит и не мутирует никакое состояние внутри самой `aig_network` (все
операции над `ntk` — `const`-методы, читающие неизменяемое хранилище
графа), поэтому конкурентные вызовы `simulate()` на одной и той же
const-сети из разных OpenMP-потоков безопасны структурно, без гонок.

**Найдено `benchmarks/large_scale_bench.cpp` (по запросу пользователя
"проверь функции без прироста скорости — есть ли ещё возможность
ускориться"): несмотря на доказанную безопасность, реальный speedup на
n=12..24 был ~1.00x — параллелизм не давал НИКАКОГО эффекта, не только
малого.** Причина не в гонках/локах (их тут нет вовсе), а в фиксированной
цене ОДНОГО вызова `simulate()`: внутри — аллокация `node_map` плюс
**отдельный** `std::vector<SimulationType> fanin_values` на КАЖДЫЙ гейт
сети (`algorithms/simulation.hpp`). Раньше блок был 6 "свободных"
переменных (K=6, 64 бита/вызов): при n=24 это `num_blocks=2^18=262144`
вызовов `simulate()`, на каждый — десятки мелких куч-аллокаций через
glibc-аллокатор, при том что полезная работа на блок — единицы AND/XOR над
64-битным словом (наносекунды). Итог: время съедалось malloc/free и
fork-join OpenMP, а не вычислениями.

**Исправлено**: ширина блока увеличена с K=6 до `kBlockVars=10` (1024
бита/вызов вместо 64) — тот же суммарный объём полезной работы, но в
2^(10-6)=16 раз меньше вызовов `simulate()`, а значит в 16 раз меньше
аллокаций `node_map`/`fanin_values` на весь запуск.
`kitty::static_truth_table<K>` для K>6 хранит `std::array<uint64_t,
NumBlocks>` с обычными `begin()/end()` (проверено в
`kitty/static_truth_table.hpp`) — блок копируется целиком через
`std::copy` вместо ручного побитового разбора одного `uint64_t`, как было
раньше.

**Замер на одной и той же локальной машине, до/после, честно
(`test_aig` — `aig_to_tt PASS` в обоих случаях, корректность не
затронута):**

| n | до фикса (K=6): 1 поток / N потоков | после фикса (K=10): 1 поток / N потоков | ускорение по абсолютному времени (1 поток) |
|---|---|---|---|
| 12 | 0.04 / 0.04 мс (1.00x) | 0.01 / 0.01 мс (1.00x) | ×4 |
| 16 | 0.70 / 0.69 мс (1.00x) | 0.10 / 0.10 мс (1.00x) | ×7 |
| 20 | 12.37 / 13.45 мс (0.92x) | 2.74 / 2.92 мс (0.94x) | ×4.5 |
| 24 | 352.71 / 338.20 мс (1.04x) | 61.25 / 59.81 мс (1.02x) | ×5.8 |

**Важная оговорка**: столбец "ускорение" — это АБСОЛЮТНОЕ время (реальный,
измеримый выигрыш для любого пользователя библиотеки, независимо от числа
ядер), а не эффект от параллелизма. Отношение "1 поток / N потоков" внутри
каждой ячейки почти не изменилось (было ~0.92-1.04x, осталось ~0.94-1.02x)
— фикс уменьшил фиксированные накладные расходы, влияющие на ОБА режима
одинаково, а не что-то специфичное для многопоточности. Честный вывод:
`aig_to_tt` на тестируемых размерах (синтетические AIG ~2n гейт) остаётся
функцией, где параллелизм сам по себе не окупается — полезной работы на
блок физически слишком мало относительно любых накладных расходов
(OpenMP fork-join, аллокации), но само по себе распараллеливание корректно
и безопасно, а абсолютная скорость реально выросла.

**Оговорка про разброс между прогонами**: повторный полный прогон
`large_scale_bench` (все 12 функций подряд, а не изолированно) дал для
n=20/24 несколько другое отношение "1 поток / N потоков" (0.68x и 0.94x
вместо 0.94x и 1.02x выше) при почти той же абсолютной скорости
однопоточного варианта (3.21мс/65.37мс против 2.74мс/61.25мс) — на таких
малых абсолютных временах (единицы-десятки мс) OpenMP fork-join шум и
загрузка машины другими процессами заметно двигают именно ОТНОШЕНИЕ, но
не меняют вывод: абсолютное время устойчиво в разы меньше, чем до фикса, а
относительный speedup остаётся в шумовом диапазоне около 1.0x в обоих
прогонах.

## 2. Разнообразный корпус, n до 64 (aig_to_bdd/aig_to_anf)

Тот же набор структурных семейств, что и в `anf/README.md` §5.2 (chain,
star/hub, block, one-hot mux, random sparse), построенных напрямую через
`mockturtle::aig_network` (`create_and`/`create_xor`, без `tt_to_aig` —
та ограничена n<=24). Корректность проверялась на 200 случайных точках на
семейство/размер против независимого эталонного вычислителя той же формулы
(exhaustive невозможен при n=64) — **все случаи, все размеры: OK**, ни
одного расхождения.

| семейство (n=64) | aig_to_bdd NodeCount | aig_to_bdd время, мс | aig_to_anf speedup (1 vs N потоков) |
|---|---|---|---|
| chain | 127 | 2.7 | 1.25 |
| star/hub (центр x_63) | 127 | 3.5 | 1.39 |
| block (клики по 4) | 65 | 0.4 | 1.06 |
| one-hot mux 4×7 (n=60) | 4771 | 22.1 | 1.59 |
| random sparse (n=32, максимум для этой серии) | 13791 | 19.2 | 1.88 |

`aig_to_bdd`-числа для chain/star/block **буквально совпадают** с
`min_index`-строкой из таблицы `anf/README.md` §5.2 — ожидаемо: `aig_to_bdd`
использует тот же натуральный PI-порядок, что и эвристика `MinIndex` в
`anf_to_bdd`, и обе стороны компилируют одну и ту же функцию через один и
тот же принцип "BDD уровень == индекс переменной" (`core/CONVENTIONS.md`
п.1) — разные входные представления (AIG vs ANF) одной и той же логической
функции при одинаковом порядке переменных дают один и тот же ROBDD (снова
теорема Брайанта о канонической форме). Как и в `anf/`, семейство `random`
на большем n показывает экспоненциальный рост NodeCount (221 → 1711 →
13791 при n=16/24/32) — то же математическое свойство неструктурных
функций, не специфика AIG-пути (см. `anf/README.md` §6 за объяснением
через cutwidth/bandwidth). `aig_to_anf`-speedup колонка — тот самый шум
вокруг 1.0-1.9x из §1.3, ожидаемо без выраженной закономерности от n или
семейства (нет реального параллелизма, который мог бы масштабироваться).

## 3. Практические выводы

- **Безопасно как есть**: `aig_to_bdd` (нет параллелизма, нечему
  ломаться), `aig_to_thr` (корректный flat-array паттерн), `aig_to_tt`
  (простая read-only параллельная симуляция).
- **`tt_to_aig`**: ИСПРАВЛЕНО в этой сессии (не только проанализировано) —
  был реальный дедлок (`entry->mtx` держался поперёк рекурсии/`tg.wait()`,
  см. §1.1), подтверждён стек-трейсом зависшего процесса, воспроизведён
  через реальный провал `ctest` (25 минут таймаут) после ужесточения
  бенчмарк-методологии (§4). Исправлено на "не блокировать, а считать
  избыточно" — 5/5 повторных прогонов без зависаний, корректность и полный
  `ctest` (36/36, 145с) подтверждены. Остаточный вопрос (не баг, а
  архитектурное ограничение) — глобальный `net_mutex`, сериализующий все
  мутации сети; на измеренных n<=16 эффект неотличим от шума (§1.1). Если
  когда-нибудь придётся ускорять `tt_to_aig` по-настоящему — точка роста
  именно здесь (снять `net_mutex`, например через thread-local буферы
  `aig_network` с последующим слиянием, тот же паттерн, что рассматривался
  и был отклонён для `anf_to_aig.cpp`, см. `anf/README.md` §7).
- **`aig_to_anf`**: ДВЕ отдельные находки, обе учтены. (1) BRiAl-ветка
  (активная в этой сборке) — TBB отключён правильно, это не баг, а
  требует только правки документации (явный комментарий в
  `aig_to_anf.cpp`/`.hpp`, почему TBB-форк недоступен, со ссылкой на этот
  README + TSan-находку §1.3 — сам код документации ещё не дописан, это
  открытый TODO). (2) `AnfFallback`-ветка (не активна в этой сборке) —
  ИСПРАВЛЕНА в этой сессии: содержала тот же дедлок-паттерн (mutex поперёк
  `tg.wait()`), что и `tt_to_aig.cpp` (§1.1), найден при целенаправленной
  проверке ПОСЛЕ фикса `tt_to_aig.cpp` (не был бы пойман прогоном тестов
  в этом образе — BRiAl здесь всегда доступен, эта ветка никогда не
  компилируется в тестовый бинарь). Исправлен код, но живым прогоном
  именно этой ветки проверить не удалось (см. §1.3, "не проверено живым
  прогоном"). Дополнительно стоит рассмотреть, не сделать ли в
  `core/CONVENTIONS.md` п.6 явное исключение для функций, работающих с
  `BoolePolynomial` на одном общем `BoolePolyRing` — сейчас формулировка
  правила подразумевает, что TBB всегда возможен для `aig_to_*`/`anf_to_*`,
  что для BRiAl-веток не так.

## 4. Методология бенчмарков исправлена (медиана вместо единичного замера)

По отдельному запросу пользователя ("исправь тесты, чтобы были адекватные
данные") — `measure_scaling()`/`measure_scaling_omp()`
(`benchmarks/tbb_scaling.hpp`/`benchmarks/openmp_scaling.hpp`) раньше
делали ОДИН замер на каждую сторону (1 поток / все ядра) после одного
прогрева. На суб-миллисекундных функциях (типичные размеры тестового
набора) единичный замер — в основном шум OS-планировщика, не сигнал.
Исправлено на 1 прогрев + **медиана 5 независимых повторов** на каждую
сторону — общий фикс для ВСЕХ `*_tbb_scaling`/`*_openmp_scaling` секций
проекта разом (`benchmarks/*.hpp` — общая инфраструктура для `test_aig.cpp`/
`test_anf.cpp`/`test_thr.cpp`), не только для `aig/`.

Заодно исправлен `print_bench_summary()` (`benchmarks/scaling.hpp`):
раньше итоговая строка ("ускорение до xN") бралась как **MAX** speedup
среди всех размеров — при шумных данных это систематически завышало
впечатление о параллелизме, выбирая самый "везучий" размер (конкретный
пойманный случай: `aig_to_anf` — {0.92, 1.27, 1.02} превращались в
заголовок "ускорение до x1.27", хотя реального параллелизма там нет вообще,
см. §1.3). Теперь — МЕДИАНА speedup по всем размерам + явная пометка, если
знак эффекта не согласован между размерами ("результат непоследователен...
не делайте выводов по одному размеру").

**Побочный эффект фикса — вскрыл реальный дедлок**: увеличение числа
вызовов на размер (было 1+1+1=3, стало 1+5+5=11) подняло вероятность
попадания в дедлок `tt_to_aig.cpp` настолько, что полный `ctest` реально
завис на 25 минут и провалился по таймауту — см. §1.1 за диагностикой и
фиксом. Число повторов сознательно взято 5, не 11 (как в разовых
диагностических бенчмарках этой сессии) — некоторые из бенчмаркуемых
функций (`aig_to_thr`/`anf_to_thr` — ILP-solve, `tt_to_anf` — Мёбиус-
трансформ) на `kMaxReferenceAigVars=14` уже стоят ~1-2с ЗА ОДИН вызов, 11
повторов ощутимо утяжелили бы каждый `ctest`-прогон.

## 4а. BRiAl vs AnfFallback — правда ли BRiAl ограничивает параллелизм, и что даёт отказ от него

Прямой вопрос пользователя после §1.3/§1.1: "правда ли BRiAl блокирует
многопоточность, и можем ли мы получить БОЛЬШЕ параллельности без неё?".
TSan-находка (§1.3) уже отвечает "да, правда" — но не показывает, ЧТО
конкретно можно выиграть/потерять, если реально переключиться на
`AnfFallback` (которая, в отличие от BRiAl, не имеет разделяемого
CUDD-подобного менеджера и структурно НЕ подвержена этому классу гонок).

Добавлен `BMM_FORCE_ANF_FALLBACK` (`core/anf_repr.hpp`, тот же паттерн, что
`BMM_FORCE_VARIANT_FALLBACK` для `Result<T>` в `core/common.hpp`) —
форсирует `AnfFallback`-ветку независимо от того, физически доступен ли
BRiAl в include-путях. Собран временный (`aig/bench_anf_fallback.cpp`,
удалён после записи чисел) отдельный исполняемый файл со СВОЕЙ копией
`aig/aig_to_anf.cpp`, скомпилированной с этим макросом, на ТОМ ЖЕ корпусе,
что и §2 (chain/star/block/mux/random). Заодно это был первый живой прогон
именно `AnfFallback`-ветки после фикса дедлока в §1.3 (там я честно
написал, что проверить её вживую не смог) — прогнано без единого
зависания, corrrectness OK на всех случаях, вопрос из §1.3 закрыт: фикс
работает и в этой ветке тоже.

**Результат** (абсолютное время `aig_to_anf`, BRiAl — медиана 1 потока из
предыдущего раунда §2, AnfFallback — медиана 1 потока из нового прогона):

| случай (n) | BRiAl, мс | AnfFallback, мс | во сколько раз AnfFallback МЕДЛЕННЕЕ |
|---|---|---|---|
| chain (16→64) | 0.035 → 0.357 | 0.560 → 58.964 | **16x → 165x** |
| star/hub (16→64) | 0.033 → 0.393 | 1.024 → 34.425 | **31x → 88x** |
| block (16→64) | 0.012 → 0.055 | 0.036 → 1.105 | **3x → 20x** |
| one-hot mux (n=21→60) | 0.024 → 0.190 | 0.209 → 4.032 | **9x → 21x** |
| random sparse (16→32) | 0.055 → 0.216 | 0.891 → 7.822 | **16x → 36x** |

**И это BEZ учёта параллелизма** — сравнение "1 поток BRiAl" vs "1 поток
AnfFallback". С параллелизмом AnfFallback СТАНОВИТСЯ ХУЖЕ, не лучше: во
всех 19 измеренных случаях, кроме двух (`chain_n64`=1.06x,
`block4_n32`=1.06x), параллельная версия AnfFallback МЕДЛЕННЕЕ
однопоточной (0.5x-0.9x) — те же самые реальные `tg.run()`/`tg.wait()`
TBB-задачи, которых в BRiAl-ветке вообще нет, здесь честно выполняются
параллельно, но накладные расходы TBB не окупаются на этих размерах входа
даже при генуинном параллелизме (тот же эффект, что у `net_mutex` в
`tt_to_aig.cpp`, §1.1 — параллелизм сам по себе не панацея, если
единица работы дешевле накладных расходов на её распределение).

**Почему разрыв в 16x-165x, и почему растёт с n**: BRiAl хранит множество
мономов как ZDD (Zero-suppressed Decision Diagram) со структурным
разделением одинаковых поддеревьев между операциями — умножение/сложение
полиномов работает через операции над ZDD-структурой, а не перебором пар
мономов. `AnfFallback` — это буквально `std::set<Monomial>`: сложение —
merge двух отсортированных множеств (нормально), но **умножение —
декартово произведение мономов** (`mul_poly` в `aig_to_anf.cpp`, вложенный
цикл по всем парам `(m1, m2)`) без какого-либо структурного разделения
между промежуточными полиномами разных узлов AIG. Разрыв растёт с n именно
потому, что структурное разделение ZDD даёт БОЛЬШИЙ выигрыш там, где
больше overlapping-структуры между промежуточными полиномами — а на
маленьких n (n=16) оверлапа мало, разрыв всего 3x-31x.

**Ответ на вопрос пользователя**: технически параллелизм БЕЗ BRiAl получить
можно (`AnfFallback` не имеет разделяемого мутабельного менеджера, поэтому
структурно не подвержена гонке, и её TBB-ветка теперь, после фикса
дедлока, реально работает) — но это плохой обмен: вы получаете
"настоящий", но не окупающийся параллелизм (0.5x-0.9x) ценой алгоритма,
который на n=64 уже в 88-165 раз медленнее в один поток. Правильный путь к
БОЛЬШЕЙ параллельности без потери скорости BRiAl — не отказ от BRiAl, а
одно из:

1. **Отдельный `BoolePolyRing` на поток** (если BRiAl это вообще
   позволяет — не проверено в этой сессии): каждый поток получает СВОЙ
   CUDD-менеджер, без разделяемого мутабельного состояния, значит без
   гонки по построению; но результаты из разных ring'ов, вероятно, нельзя
   комбинировать напрямую (нужна явная конвертация/сериализация на
   границах) — архитектурно нетривиально, не проверено эмпирически.
2. **ZDD-аналог Sylvan для представления множества мономов** — тот же
   принцип, что уже используется в этом проекте для BDD (`core/
   CONVENTIONS.md`: Sylvan выбран вместо CUDD именно из-за потокобезопасной
   архитектуры на Lace) — но для ANF готового решения в текущем стеке
   зависимостей нет, пришлось бы либо искать сторонний потокобезопасный
   ZDD-пакет, либо писать свой. Существенный объём работы, не в скоупе
   этой сессии.
3. **Оставить как есть** — BRiAl-путь фактически последователен, но
   быстрый; накладные расходы честного TBB-параллелизма на
   `AnfFallback`-масштабах входа (n<=64) всё равно не окупаются даже без
   учёта разрыва в 16x-165x, так что "больше параллельности" здесь не
   значит "быстрее" ни при каком из проверенных вариантов.

`BMM_FORCE_ANF_FALLBACK` оставлен в `core/anf_repr.hpp` (не удалён вместе
с временным бенчмарком) — низкий риск (неактивная `#if`-ветка, пока макрос
явно не передан через `-D`), но полезен для будущих аналогичных проверок
без пересборки Docker-образа без BRiAl.

## 5. Как повторить

Оба диагностических инструмента (`aig/stress_brial_threads.cpp` под
`-fsanitize=thread`, `aig/bench_aig_corpus.cpp` с корпусом до n=64) были
временными и удалены из финального диффа после того, как числа записаны
здесь — тот же паттерн, что и у `anf/bench_*.cpp` (см. `anf/README.md`).
Полная история находок этой сессии, включая тупиковые ветки (первый прогон
бенчмарка без прогрева, давший ложные 20x-90x) — в памяти Claude Code
этого проекта, недоступна вне сессий с тем же механизмом памяти.

## 6. `aig_to_anf`: пересланная "история изменений" не совпадала ни с одним
##    реальным состоянием кода — разбор, чужая ветка, реальный фикс, замеры

Отдельная сессия началась с того, что пользователь прислал markdown-файл
(`aig_to_anf_history.md`, вне репозитория), якобы описывающий хронологию
правок `aig_to_anf.cpp` вплоть до "финальной версии" (рекурсия+`shared_ptr`
из более ранней сессии + отсечки `isZero()/isOne()/p0==p1` в `mul_poly` +
переписанный без `substitute_variables` `Anf::evaluate`, "все тесты 0.7-1.0
сек"). Задача — жёстко сверить этот текст с реальным кодом.

**Результат сверки: ни отсечки в `mul_poly`, ни фикс `Anf::evaluate` не
существовали НИГДЕ** — не в рабочем дереве, не в единственном коммите,
трогавшем эти файлы (`46a1d7d`), не на `origin/aig`/`origin/anf`/
`origin/Thr`/`origin/master` — проверено `git log --all -p -- aig/
aig_to_anf.cpp core/anf_repr.hpp core/common.hpp | grep "isZero\|p0 == p1"`
(0 совпадений) на момент начала разбора. Это учебный монорепозиторий на
несколько студентов (ветки `aig`/`anf`/`Thr`/`egor`, разные email авторов),
и `aig_to_anf.cpp` на HEAD пользователя (рекурсия + `shared_ptr<MemoEntry>`
+ `tbb::concurrent_hash_map`, TBB реально работает только в `AnfFallback`,
см. §1.3 выше) не единственная реализация в репозитории — на `origin/aig`
независимо от неё существует совсем другая, написанная другим автором
(`ondarao@mail.ru`, коммиты `d4cdfa2`/`596ed77`/`2db40e7`): топологический
`foreach_gate` без рекурсии, без TBB вообще, без `shared_ptr`/хэш-таблицы —
мемоизация просто индексом в `std::vector<BoolePolynomial>`.

**Пока шла сверка, в репозиторий пришёл новый пуш** (`git fetch` посреди
разговора внезапно подтянул новый коммит) — `4dcdc15` того же автора,
сообщение "some problems with anf": он ДОБАВИЛ ровно отсечки
`isZero()/isOne()/p0==p1` в свою топологическую версию на `origin/aig`.
То есть половина заявленного в присланной истории на тот момент реально
появилась в репозитории — но написана другим человеком, в другой
архитектуре (без рекурсии/TBB), только что, и без второй половины
(`Anf::evaluate` там всё ещё звал `substitute_variables`). Совпадение
текста истории с реальным состоянием кода на любой момент времени, любой
ветки, любого автора — не подтвердилось ни разу; наиболее вероятное
объяснение — пересказ работы, которая делалась в песочнице/контейнере и не
была закоммичена, либо смешение нескольких сессий/авторов в одном тексте.

**Тот же коммит `4dcdc15` откатил (не связанные с ANF) уже закрытые баги** в
`verify/`: убрал привязку входов `PI_a_i == PI_b_i` между двумя схемами в
`verify/sat_encoding/sat_encoding.cpp` (без неё SAT-солвер почти всегда
находит "эквивалентность" для НЕэквивалентных схем — весь шаг 3 в
`verify/test_runner.hpp` перестаёт что-либо ловить, не только для
`aig_to_anf`), вернул `theta_dist(-sum, sum)` на знаковой сумме весов в
`verify/reference_builders.cpp` (UB при `sum<0`: `uniform_int_distribution`
с `a>b`), и поднял `kMaxGroundTruthVars` обратно с 12 до 16. На master
(`HEAD`) все три места по-прежнему в правильном, уже проверенном состоянии
— проверено `git show HEAD:verify/sat_encoding/sat_encoding.cpp` /
`reference_builders.cpp` / `verify/ground_truth/ground_truth.hpp` до начала
правок ниже. Вывод по сравнению "какая версия лучше": ни одна целиком —
`origin/aig` даёт реальный алгоритмический выигрыш в самом
`aig_to_anf.cpp`, но откатывает верификационную инфраструктуру; смешивать
нужно избирательно, не мёржить ветку целиком.

### Что реально сделано в `aig_to_anf.cpp`/`core/anf_repr.hpp`

По итогам сравнения собран гибрид, НЕ импортирующий `verify/`-регрессии
`origin/aig`:

1. **BRiAl-ветка (`#if BMM_HAVE_BRIAL`, активная в production) переписана**
   с рекурсии+`shared_ptr<MemoEntry>`+`concurrent_hash_map` на топологический
   `net.foreach_gate` над плоским `std::vector<PolType>` — та сложность не
   покупала параллелизма (см. §1.3: TBB в этой ветке и раньше не
   выполнялся), только усложняла чтение. Мемоизация — просто индекс в
   массиве, за счёт инварианта mockturtle (индекс фанина всегда меньше
   индекса узла).
2. **`mul_poly` теперь отсекает `isZero()/isOne()/p0==p1` — для ОБЕИХ
   реализаций**, BRiAl и `AnfFallback` (в `origin/aig` это было только для
   BRiAl). `P·P=P` — не частный случай, а тождество для любого элемента
   булева кольца `GF(2)[x]/(x_i^2-x_i)` (кольцо характеристики 2: `(P+Q)² =
   P²+Q²`, по индукции от одночленов любой многочлен идемпотентен).
3. **`Anf::evaluate` (`core/anf_repr.hpp`) переписан** с
   `substitute_variables(ring, idx2poly, poly_)` (пересборка всего ZDD на
   КАЖДЫЙ вызов) на прямой проход по термам полинома (`BoolePolynomial::
   const_iterator` → `BooleMonomial::const_iterator` → индексы переменных)
   — тот же алгоритм, что уже был в `AnfFallback::evaluate`. Осиротевший
   `using polybori::substitute_variables` и его инклюд убраны.
4. **Доккомментарий в `aig_to_anf.hpp` обновлён** — больше не заявляет TBB
   как обязательный для этой функции без оговорок, ссылается на §1.3 этого
   README.
5. `AnfFallback`-ветка (`#else`) и `get_ring()` (кэш на один слот, ключ
   "последний использованный n" — см. §1.3) **не тронуты**: первая и так
   корректна и параллельна, второй — известный, но отдельный от этой задачи
   риск (мьютекс защищает только своп указателя, не время жизни уже
   выданных `BoolePolynomial` при конкурентном вызове с разными n; не
   проверялось, держит ли `BoolePolyRing`/`CCuddCore` собственный refcount
   независимо от кэша — остаётся открытым TODO).

### Реальная сборка и замеры (не только чтение кода)

BRiAl доступен только в Docker/Coder-окружении — локальной Windows-машины
недостаточно. Полная пересборка `.devcontainer/Dockerfile` с нуля **не
проходит сейчас вообще**, и это НЕ следствие правок этой сессии: BRiAl
клонируется без фиксации тега (`git clone --depth 1` на upstream HEAD), а
актуальный BRiAl (включая тег `1.2.15`, `configure.ac`) требует `m4ri >=
20250128`, тогда как `libm4ri-dev` из Ubuntu 24.04 даёт `20200125` — apt-
пакет устарел относительно требования upstream-библиотеки. Для проверки
собран урезанный образ (без CUDA-базы/SageMath/PyTorch — не нужны для
C++-тестов) с `m4ri`, собранным из исходников (git HEAD, `20260122`) вместо
системного пакета. Отдельно: `cmake --build -j$(nproc)` на сборке OR-Tools
(`-DBUILD_DEPS=ON`, protobuf/abseil с нуля) дважды ронял соединение с
Docker-демоном на 12GB VM — похоже на OOM; помогло `-j4` для этого шага.
Если понадобится пересобрать `.devcontainer/Dockerfile` "как есть" —
сначала поправить версию BRiAl/m4ri там же.

**Замеры на пересобранном образе:**

| Проверка | Результат |
|---|---|
| Компиляция (`BMM_HAVE_BRIAL=1`) | чисто, `test_aig`/`test_anf` линкуются |
| `aig_to_anf` (ground_truth+metamorphic, n=1..12) | PASS, 1/1 |
| Один вызов `aig_to_anf()` (n=8/12/14) | 0.024 / 0.047 / 0.063 мс |
| `speedup` 1 поток vs все ядра | 0.90 / 1.07 / 1.00 — шум, подтверждает §1.3 |
| Полная секция `aig_to_anf` целиком | **6m44s** |

Последняя строка **не противоречит** остальным — это не медленность самого
`aig_to_anf()` (0.02-0.06 мс на вызов), а стоимость верификационной
обвязки: `TEST_CASE("aig_to_anf")` → `run_translation_tests()`
(`verify/test_runner.hpp`) на ~190 тестовых функциях (`growing_test_
functions(12)`) вызывает `aig_to_anf()` ОДИН раз на функцию, а следом —
`find_mismatch`, `compute_chow_parameters` (дважды: src и dst),
`compare_anf_degree`, `check_cofactor_commutativity` — каждая честно
перебирает все `2^n` точек и вызывает `.evaluate()` независимо от
остальных, без переиспользования между проверками. Именно это, а не сама
трансляция, съедает 6m44s. Заявленные в присланной истории "0.7-1.0 сек на
все тесты" не подтвердились даже после реального фикса — не потому, что
фикс не помог (сама трансляция стала быстрой), а потому что число
подтверждено измерением, а не переписано из непроверяемого текста.

## 7. Лучшие практики, подтверждённые в этой папке

Не общие советы — каждый пункт восходит к конкретной находке выше (см.
ссылку), это то, что стоит переносить в другие функции проекта, а не
изобретать заново.

1. **Мьютекс на memo-запись защищает только мгновенную публикацию готового
   результата, никогда не удерживается поперёк рекурсии/ожидания.**
   Реальный дедлок в `tt_to_aig.cpp` (§1.1) и тот же паттерн, найденный
   (но не пойманный тестами в этой сборке) в `AnfFallback`-ветке
   `aig_to_anf.cpp` (§1.3) — оба случая: `lock_guard` держался поперёк
   `tg.wait()`, поток-ожидающий сам становился недоступен TBB-планировщику
   как воркер, арена исчерпывалась. Фикс один и тот же везде: если нужный
   узел ещё не готов — считать его самостоятельно и избыточно, а не ждать
   чужую работу под локом.
2. **Топологический обход с индексом-в-массиве вместо
   рекурсии+хэш-таблицы+`shared_ptr`, когда порядок обхода гарантирует, что
   зависимости уже посчитаны.** `aig_to_anf.cpp` переписан в §6 именно так:
   `net.foreach_gate` + `std::vector<PolType>`, индексированный
   `node_to_index` — инвариант mockturtle (индекс фанина всегда меньше
   индекса узла) делает мемоизацию через хэш-таблицу с мьютексами и
   atomic-флагами избыточной сложностью, если TBB в этой ветке всё равно не
   работает (см. следующий пункт).
3. **Если библиотека не потокобезопасна — не притворяться, что параллелизм
   есть, и объяснять почему в коде, а не только "в голове".** BRiAl/CUDD
   не потокобезопасен (TSan подтвердил гонку в `CCuddCore::release()`,
   §1.3) — правильный ответ был не "обернуть в мьютекс" (создало бы
   узкое место без выигрыша) и не "притвориться, что TBB работает"
   (создавало бы ложное ощущение соответствия `CONVENTIONS.md`), а
   последовательный код с явным doc-комментарием, ссылающимся на находку
   (сделано в этой сессии в `aig_to_anf.hpp`, см. §6).
4. **Извлекать POD-структуры без указателей на общий объект ДО параллельного
   участка**, если сама библиотека не даёт гарантий безопасности
   конкурентного чтения. `aig_to_thr` (§1.4) — эталон: узлы AIG вытащены в
   плоский `std::vector<FlatGate>` до `tbb::parallel_for`, каждый поток
   пишет только в свой слот результата — реальный измеренный speedup
   растёт с n (0.94→1.14→1.53), а не шум вокруг 1.0.
5. **Провести тождества алгебраической структуры — это бесплатная
   оптимизация, если она гарантированно верна, а не эвристика.** `P·P=P`
   для ЛЮБОГО элемента булева кольца `GF(2)[x]/(x_i^2-x_i)` (не частный
   случай — свойство самого кольца, характеристика 2) — отсечки
   `isZero()/isOne()/p0==p1` в `mul_poly` (§6) экономят полное ZDD-умножение
   BRiAl на каждом AND-узле, где это применимо, без единого компромисса по
   корректности.
6. **Одноместный кэш ("последний использованный X") даёт ложные ускорения
   в бенчмарках и является скрытой угрозой при конкурентных вызовах с
   разными X.** `get_ring(n)` в `aig_to_anf.cpp` (§1.3) один раз уже дал
   ложные 20x-90x "ускорения" в бенчмарке из-за прогрева, а не потоков;
   тот же кэш остаётся неисправленным риском при параллельных вызовах с
   разными `n` (§6, открытый TODO) — единственный слот кэша не место для
   экономии, если у него есть наблюдаемые побочные эффекты на время жизни
   объектов.
7. **Единичный замер на суб-миллисекундных функциях — шум, не сигнал; MAX
   среди размеров завышает впечатление о параллелизме.** Общий фикс
   методологии (§4) — медиана 5 повторов с прогревом вместо одного замера,
   и медиана (не максимум) speedup по размерам в итоговой строке. Без
   этого фикса конкретно `aig_to_anf` выглядел бы как "ускорение до x1.27"
   вместо честного "шум вокруг 1.0, параллелизма нет" (§1.3).
8. **Незафиксированная версия внешней зависимости в Dockerfile ломает
   воспроизводимость сборки без единой строчки изменений в самом
   проекте.** `.devcontainer/Dockerfile` клонирует BRiAl без тега
   (`git clone --depth 1` на upstream HEAD) — с тех пор BRiAl поднял
   минимальное требование к `m4ri` выше версии, которую даёт `apt` в
   Ubuntu 24.04 (§6). Пересобрать образ "как есть" сегодня не получится
   вообще, независимо от кода этого репозитория — сборка внешних
   зависимостей без фиксации тега/коммита не то же самое, что
   воспроизводимая сборка.
9. **Прежде чем доверять текстовому описанию "что было сделано" (история
   чата, чужой пересказ, commit message) — сверять с `git log --all -p`
   по всем веткам, а не только с текущим HEAD.** §6 — заявленные
   исправления не существовали нигде в репозитории на момент разбора;
   часть заявленного появилась независимо, у другого автора, в другой
   архитектуре, уже во время самой проверки. Текст описания состояния кода
   и реальное состояние кода — два разных источника истины, и только
   второй авторитетен.
